In [11]:
import numpy as np
lista = range(100)
arr11=np.arange(100)

In [2]:
import sys

In [12]:
print(sys.getsizeof(87)*len(lista))

2800


In [13]:
print(arr11.itemsize*arr11.size)

800


In [19]:
import time
x = range(100000000)
y = range(100000000,200000000)

start_time = time.time()
c=[(x+y) for x,y in zip(x,y)]
print(time.time()-start_time)

2.449186086654663


In [20]:
a=np.arange(100000000)
b=np.arange(100000000,200000000)

start_time = time.time()
c=a+b
print(time.time()-start_time)

1.30216383934021


In [22]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [26]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [27]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [28]:
arr12[3:,2:]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [29]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [30]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
