In [1]:
import numpy as np

In [2]:
arr4 = np.arange(6,12).reshape(3,2)

In [3]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
arr4.ndim

2

In [5]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [6]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [7]:
arr5 = np.arange(12,18).reshape(2,3)

In [8]:
arr3 = arr4.transpose()

In [10]:
np.hstack((arr3,arr5))

array([[ 6,  8, 10, 12, 13, 14],
       [ 7,  9, 11, 15, 16, 17]])

In [11]:
np.vstack((arr3,arr5))

array([[ 6,  8, 10],
       [ 7,  9, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
arr8 = np.arange(24).reshape(6,4)

In [14]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [16]:
arr9=np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [17]:
arr9

array([[52, 95, 90, 55, 61],
       [15, 16,  7, 78, 57],
       [84, 55,  5,  5, 18],
       [25, 60, 56, 71, 34]])

In [18]:
arr9>50

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True,  True,  True, False]])

In [20]:
#Indexing using boolean array
arr9[arr9>50]

array([52, 95, 90, 55, 61, 78, 57, 84, 55, 60, 56, 71])

In [22]:
arr9[(arr9>50) & (arr9%2!=0)]

array([95, 55, 61, 57, 55, 71])

In [23]:
arr9[(arr9>50) & (arr9%2!=0)]=0
arr9

array([[52,  0, 90,  0,  0],
       [15, 16,  7, 78,  0],
       [84,  0,  5,  5, 18],
       [25, 60, 56,  0, 34]])